apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: tcc
  labels:
    app: blog
    service: blog
    java-monitoring: prometheus
spec:
  ports:
    - port: 8080
      name: http-monitoring-prometheus
      protocol: TCP
      targetPort: 8080
    - port: 80
      name: http-80
      protocol: TCP
      targetPort: 8080
  selector:
    app: blog
