apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: blog-rule
  namespace: istio-system
spec:
  host: blog
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blog
  namespace: istio-system
spec:
  hosts:
    - "*"
  gateways:
    - bookinfo-gateway
  http:
    - match:
      - uri:
        prefix: /blog/
      route:
        - destination:
            host: blog.tcc.svc.cluster.local
            subset: v1
