apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: demo
  labels:
    app: blog
spec:
  ports:
    - port: 80
      name: http-80
      protocol: TCP
      targetPort: 8080
  selector:
    app: blog
